python -m analyze_embedding \
    --output_table etsy-search-ml-dev:yzhang.visual_diversity_vsv2_explore \
    --output_dir gs://training-dev-search-data-jtzn/users/yzhang/tmp \
    --runner DataflowRunner \
    --project etsy-search-ml-dev \
    --region us-central1 \
    --service_account_email sa-dataflow@etsy-search-ml-dev.iam.gserviceaccount.com \
    --temp_location gs://training-dev-search-data-jtzn/users/yzhang/tmp/temp \
    --staging_location gs://training-dev-search-data-jtzn/users/yzhang/tmp/staging \
    --experiment use_runner_v2 \
    --experiment upload_graph \
    --experiment max_workflow_runtime_walltime_seconds=43200 \
    --machine_type e2-standard-16 \
    --disk_size_gb 200 \
    --num_workers 16 \
    --max_num_workers 32
