python -m analyze_embedding \
    --output_table etsy-search-ml-dev:yzhang.visual_diversity_vsv2_explore \
    --output_dir gs://etsy-sr-etl-prod-dataflow-staging-u8xp62t/yzhang \
    --runner DataflowRunner \
    --project etsy-sr-etl-prod \
    --region us-central1 \
    --temp_location gs://etsy-sr-etl-prod-dataflow-staging-u8xp62t/yzhang/temp \
    --staging_location gs://etsy-sr-etl-prod-dataflow-staging-u8xp62t/yzhang/staging \
    --experiment use_runner_v2 \
    --experiment upload_graph \
    --experiment max_workflow_runtime_walltime_seconds=43200 \
    --machine_type n2-highmem-8 \
    --disk_size_gb 200 \
    --num_workers 8 \
    --max_num_workers 16
